tags:
  - VSCode
  - Tools
  - ""
title: Simple OpenAPI Viewer
description: A VS Code extension to quickly view openapi.
image: https://github.com/rahuldhole/simple-openapi-viewer/raw/HEAD/resources/hero.png
url: https://simple-openapi-viewer.rahuldhole.com/
date: 15/04/2026
